package cz.belli.skodabackend.model.dto;

import cz.belli.skodabackend.api.pushnotification.PushTokenEntity;
import lombok.Getter;
import lombok.Setter;

import javax.validation.constraints.NotNull;

@Setter
@Getter
public class PushTokenDTO {

    /**
     * Device push token generated by FCM.
     */
    @NotNull(message = "Token is required.")
    private String token;

    /**
     * Language of the device.
     */
    private String language = "en";

    public PushTokenDTO() {
    }

    public PushTokenDTO(PushTokenEntity pushTokenEntity) {
        this.token = pushTokenEntity.getToken();
        this.language = pushTokenEntity.getLanguage().getLanguage();
    }
}
