package cz.belli.skodabackend.model.dto;

import cz.belli.skodabackend.endpoint.pushnotification.PushTokenEntity;
import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class TokenDTO {

    /**
     * Device push token generated by FCM.
     */
    private String token;

    /**
     * Language of the device.
     */
    private String language;

    public TokenDTO() {
    }
    public TokenDTO(PushTokenEntity pushTokenEntity) {
        this.token = pushTokenEntity.getToken();
        this.language = pushTokenEntity.getLanguage().getLanguage();
    }
}
